# Generated by Django 4.1.6 on 2023-02-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('font', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fontfile',
            old_name='video',
            new_name='font',
        ),
    ]
